### ISSUE TITLE
dpapi chrome --logindata filename dependency

### ISSUE THREAD

**Issue by presianbg** [skelsec/pypykatz#105]
Hi,

I've noticed that the `--logindata` from `dpapi chrome` expects exactly this file name `Login Data`, otherwise the function is silently failing / not producing any results.
 

Not sure if this a `bug` or `limitation`, but worth nothing it for the docs or the `help menu`. 

Cheers,
PY

**Comment by skelsec** [comment]
Thank you for the report! 
It was a bug, I pushed the fix just now to main.
