### ISSUE TITLE
Missing NT hashes

### ISSUE THREAD

**Issue by brunodev** [skelsec/pypykatz#12]
Mimikatz finds the following user and hash:
        msv :
         [00000003] Primary
         * Username : Bente
         * Domain   : PWNTHIS
         * NTLM     : b6758b113ce4814bd659b18a6269759d
         * SHA1     : feeb038d4ad991d8bc6a0d3bd8cacd8c5256b512
         * DPAPI    : d26ec53f1616692aa6ab125dfc592122

pypykatz does find the user but the NT hash is empty.
The only NT hash i get is the machine account

I uploaded dmp file called domain-controller.pwnthis.com.dmp

The dump is from Windows Server 2016

**Comment by skelsec** [comment]
Thx. Will look into it as soon as I got the time!

**Comment by skelsec** [comment]
sorry for the delay, still have a lot of backlog from other projects. Issue is not forgotten tho!

**Comment by skelsec** [comment]
Thank you very much for helping!
Bug has been identified and dealt with.
