### ISSUE TITLE
utf-8 nanodump + pypykatz

### ISSUE THREAD

**Issue by hastalamuerte** [skelsec/pypykatz#152]
Hello, when i try get secrets with pypykatz or mimikatz on win machine , and pypy on linux machine , facing everywhere same error - 
![image](https://github.com/skelsec/pypykatz/assets/63853227/14a9c112-ed88-421e-9acb-02608cda4a97)
![image](https://github.com/skelsec/pypykatz/assets/63853227/ad688462-9e82-40fa-a49f-5ebc73e9d696)

dump was made on windows PC with ASCII or UTF-8 language with ieroglifs. and Eng as second keyboard language.
with nanodump -  with , without -v and other flags

**Comment by skelsec** [comment]
100% sure the minidump file you generated is messed up. The error message tells you that the magic number (signature) of the minidump header not just incorrect but not even a text

**Comment by hastalamuerte** [comment]
Yep. Its dump issue. Now all ok. Closing. Possible was corrupted when transported. Thx a lot!
