### ISSUE TITLE
Minidump of LSASS through PCILeech; How?

### ISSUE THREAD

**Issue by InfiniteBSOD** [skelsec/pypykatz#165]
Hello,

Wondering what the mention of this actually means under "[LSASS Processing](https://github.com/skelsec/pypykatz?tab=readme-ov-file#lsass-processing)";
"pcileech - can dump secrets DIRECTLY via DMA of a live computer"

Now I have a [LeetDMA Pro v2](https://enigma-x1.com/store/product/49-leetdma-pro-v2/) and tried the latest version of [MemProcFS](https://github.com/ufrisk/MemProcFS-plugins?tab=readme-ov-file) and made changes into the txt which automatically enabled pypykatz.

However I received errors in the "/py/secrets"-directory after restarting MemProcFS.

Just wondering if the mention on the pypykatz main page / readme about pcileech is talking about MemProcFS and the method I outlined above.

Best Regards

**Comment by skelsec** [comment]
Hello,  
I believe @ufrisk can shed more light on this, but what I usually am doing is just to use MemprocFS to create a minidump of the LSASS process, it does that automatically for you and it's visible on the virtual filesystem.  
Then I just parse that lsass dump file with pypykatz.  
One thing to note: it is quite common that one encounters memory smearing when using these forensics tools, which can result in a corrupted minidump. This is normal, but then you'd need to either create another dump later, or adjust pypykatz's code to skip the unparsable parts.

**Comment by InfiniteBSOD** [comment]
> Hello,  
> I believe @ufrisk can shed more light on this, but what I usually am doing is just to use MemprocFS to create a minidump of the LSASS process, it does that automatically for you and it's visible on the virtual filesystem.  
> Then I just parse that lsass dump file with pypykatz.  
> One thing to note: it is quite common that one encounters memory smearing when using these forensics tools, which can result in a corrupted minidump. This is normal, but then you'd need to either create another dump later, or adjust pypykatz's code to skip the unparsable parts.

Thank you for your reply.
I believe that what you mentioned has changed since I checked both when running MemProcFS and in the [wiki](https://github.com/ufrisk/MemProcFS/wiki/FS_Process_Minidump);
* The wiki mentions that LSASS explicitly doesn't have a minidump created
* When running MemProcFS and browsing to the LSASS-process there are two txt-files in the minidump (?) folder which states that due to security reasons a minidump isn't created for LSASS

I would offer better answers but I don't have my PCILeech available right now I'm afraid.

**Comment by skelsec** [comment]
Ohh, I wasn't aware of this. Regardless, I'm pretty sure you can use an older version which did not have this limitation, alternatively I'd check the code of memprocfs and check if it's possible to reactivate this feature

**Comment by InfiniteBSOD** [comment]
Looking at the revisions for the "FS_Process_Minidump" wiki I found that the [revision on 2023-03-03](https://github.com/ufrisk/MemProcFS/wiki/FS_Process_Minidump/e724c3fd021b78acc489b1637c20c429de136711) mentions:
`The minidump.dmp file for the lsass.exe process is compatible with Mimikatz.`

A later revision on the 2023-04-21 doesn't mention LSASS at all.

So I'll try versions of MemProcFS before 2023-04-21 and report back.

**Comment by skelsec** [comment]
Yeah, it seems that the MemprocFS project has evolved away from being an offensive tool, which is sand but on the other hand understandable. I'd ask you to please keep your further findings private out of respect of the author.  
Thank you!

**Comment by InfiniteBSOD** [comment]
> Yeah, it seems that the MemprocFS project has evolved away from being an offensive tool, which is sand but on the other hand understandable. I'd ask you to please keep your further findings private out of respect of the author. Thank you!

Sure thing.
Might I suggest removing or rephrasing the mention of PCILeech on [pypykatz front page](https://github.com/skelsec/pypykatz?tab=readme-ov-file#lsass-processing) though?
`pcileech - can dump secrets DIRECTLY via DMA of a live computer`

Appreciate your work and will try stuff out but keep it private.

**Comment by skelsec** [comment]
reworded the entry.
