### ISSUE TITLE
Memory address is not in process memory space

### ISSUE THREAD

**Issue by forensenellanebbia** [skelsec/pypykatz#17]
**Error details**
Minidump: lsass.exe.10.0.10240_x86.dmp (uploaded to the URL)
Error: Exception('Memory address 0x%08x is not in process memory space' % requested_position)
Exception: Memory address 0x622160d5 is not in process memory space

**Operating system details**
OS name: Windows 10 Home
CPU architecture: x86
OS version: 10.0.10240
msv1_0.dll timestamp: 07/10/2015 09:24

**Pypykatz installation**
Pypykatz installed through _git clone_ on Ubuntu 18.04.2 with Python 3.6.7. Thanks!

**Comment by skelsec** [comment]
how do you keep finding these?! You are the first one to submit a new memory misalignment issue :)
Anyhow, it should be fixed now, but this is a quick fix as I don't have access to my test VMs, so the actual code might change in the future. Rest assured the minidumps will be incorporated in the test cases, so it will not cause errors in the future.
Thank you for the submission!

**Comment by vysecurity** [comment]
INFO:pypykatz:pypyKatz version: 0.4.2
INFO:pypykatz:CPU arch: X64
INFO:pypykatz:OS: Windows 10
INFO:pypykatz:BuildNumber: 18363
INFO:pypykatz:MajorVersion: 6
INFO:pypykatz:MSV timestamp: 1377564045
