### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by PotatoDrug** [skelsec/pypykatz#21]
https://github.com/skelsec/pypykatz#why-do-i-need-these-dumps-files

In order to create mimikatz in Python one would have to create structure ~difinitions~ definitions of a gazillion different structures...

**Comment by TopKeingt** [comment]
Reason for this parameter to exist: In order to choose the correct structure for parsing we need the ~~tiomestamp~~ timestamp info of the msv dll file. Rekall sadly doesnt always have this info for some reason, therefore the parsing may be failing.

**Comment by skelsec** [comment]
thx
