### ISSUE TITLE
Problem with Windows Server 2012 parsing

### ISSUE THREAD

**Issue by skelsec** [skelsec/pypykatz#27]
Hello! Using the GitHub repository version, I have the same error but with a different memory address. I tried on a lsass dump from a Windows Server 2012 (uploaded).

`pypykatz minidump SRVDC_lsass_iquaclMozy.dmp`

![2019-07-23_14-31](https://user-images.githubusercontent.com/17183864/61712468-b3645300-ad56-11e9-83d1-9104bbfc7bb4.png)

`DEBUG:pypykatz:===== BASIC INFO. SUBMIT THIS IF THERE IS AN ISSUE =====`
`DEBUG:pypykatz:CPU arch: X64`
`DEBUG:pypykatz:OS: Windows Server 2012`
`DEBUG:pypykatz:BuildNumber: 9200`
`DEBUG:pypykatz:MajorVersion: 6 `
`DEBUG:pypykatz:MSV timestamp: 1343260942`
`DEBUG:pypykatz:===== BASIC INFO END =====`

Mimikatz's works with the dump.

_Originally posted by @alexandreborgo in https://github.com/skelsec/pypykatz/issues/26#issuecomment-514194739_

**Comment by skelsec** [comment]
thx for the upload, will check it as soon as I feel less like a potato

**Comment by skelsec** [comment]
okay, can you check now with a new pull from GH?
alignment issues :(

**Comment by alexandreborgo** [comment]
It is working \o/, thank you for the quick fix :)
