### ISSUE TITLE
'Namespace' object has no attribute 'minidump'

### ISSUE THREAD

**Issue by jaimefoo** [skelsec/pypykatz#29]
Hi,
I just followed all the installation instructions through pip3, including all necessary modules.
All is installed in an ubuntu 18.04 server virtualbox.

I just provide SAM and SYSTEM files and need to have the hashes dumped.
I do:
`pypykatz dpapi --system ./SYSTEM --sam ./SAM credential`

And I get:
`'Namespace' object has no attribute 'minidump'`

I also do: 
`pypykatz dpapi --system ./SYSTEM --sam ./SAM vault`

And I get:
`'Namespace' object has no attribute 'vpol'`

What is going on? Do you know of another method to do the same?

Thanks!

**Comment by skelsec** [comment]
Ughh, you are right, fixing this mess as soon as I get my machine back.
Alternatively you can use the dpapi script from impacket [here](https://github.com/SecureAuthCorp/impacket/blob/master/examples/dpapi.py)
Will get back to you when it's fixed.

**Comment by skelsec** [comment]
Did a major rewrite on the dpapi command line helper, and added some fixes.
Please check the "devel" branch and let me know if it helped.
Please also note that the command have changed significantly :)

**Comment by skelsec** [comment]
No reply, so I consider this issue solved.
