### ISSUE TITLE
Implement dpapi::chrome module

### ISSUE THREAD

**Issue by jarlethorsen** [skelsec/pypykatz#47]
Hi,

I've started looking into what it will take to implement a function like the updated dpapi::chrome module found in Mimikatz:

![image](https://user-images.githubusercontent.com/859603/77633045-2a3d9580-6f4f-11ea-8adf-fa68d543e62f.png)

Code found here: https://github.com/gentilkiwi/mimikatz/blob/b098bf37cf71581882e6a1fa45ac58ec87860fd5/mimikatz/modules/dpapi/packages/kuhl_m_dpapi_chrome.c

As far as I can tell the first obstacle is that pypykatz currently has no bcrypt implementation.

Do you have any thoughts on how this should be implemented?

I'm primarily looking for an offline solution (getting keys from sid/password).

**Comment by skelsec** [comment]
The next version [0.4.0](https://github.com/skelsec/pypykatz/tree/dev4) in beta currently will fix this issue.
