### ISSUE TITLE
go_live() giving exception after screen lock on win10

### ISSUE THREAD

**Issue by hwrnr** [skelsec/pypykatz#53]
After locking and unlocking screen on windows 10 (Build 19041), go_live() function would raise "Exception: Would read over segment boundaries!". After some time, it would work again.
I tried 'pypykatz live lsa' and running it from lazagne project, with the same thing happening.

**Comment by skelsec** [comment]
Yeah, I can confirm this is happening since forever. To be honest I could not identify the cause of this.
Will keep this issue open if more ppl state that it's a breaking issue then I'll spend more time looking into this.

**Comment by skelsec** [comment]
Noone encountered this issue it seems (or noone commented here).
