### ISSUE TITLE
Namespace' object has no attribute 'out_file'

### ISSUE THREAD

**Issue by Papotito123** [skelsec/pypykatz#55]
Hello:
I have lazagne that already install pypykatz.
Collecting https://github.com/skelsec/pypykatz/archive/master.zip (from -r C:\lozogno\requirements.txt (line 7))
  Using cached https://github.com/skelsec/pypykatz/archive/master.zip
Requirement already satisfied (use --upgrade to upgrade): pypykatz==0.3.12 from https://github.com/skelsec/pypykatz/archive/master.zip in c:\python37\lib\site-packages (from -r C:\lozogno\requirements.txt (line 7))

I can run pypykatz live/registry/nt  modules well.
Also I can run pypykatz live dpapi well.

But when trying to run pypykatz dpapi minidump ,this error throws:

C:\python37\Scripts>pypykatz dpapi minidump "C:\jibes\lsass.DMP"
Traceback (most recent call last):
  File "C:\python37\Scripts\pypykatz-script.py", line 11, in <module>
    load_entry_point('pypykatz==0.3.12', 'console_scripts', 'pypykatz')()
  File "c:\python37\lib\site-packages\pypykatz\__main__.py", line 270, in main
    dpapi.dump_masterkeys(args.out_file)
AttributeError: 'Namespace' object has no attribute 'out_file'

Any info  will be great.

Thanks.

**Comment by skelsec** [comment]
Yes, the argument was missing. I fixed it and published a new version (0.3.13). Please confirm and close if fix works.

**Comment by Papotito123** [comment]
Hello:
Win 10 1809 x64.
From lazagne :  Successfully installed pypykatz-0.3.13

I tested  dpapi minidump "C:\jibes\lsass.DMP" -o "C:\jibes\dpapis.txt"  ,and dpapis.txt gives likes this:

{
    "backupkeys": {},
    "masterkeys": {
        "15e43b11-4cee-437f-928e-082807c02474": "c6cd637b001a5d7a54659605e6cf5f14f03cb4f28139cab8db44112e61de7032c10ac64a3f5b991e4e4d2a93a23f5f656646dd5966dfd553ced90d471b6d01c3",
        ''
        ''
        "
        ''
    }
}

I see SHA1 matching pair is not calculated,Is not that mkey  key doesn't being of use.Other tools bring sha1 and is shorter.

The fix works.

So much thanks.

**Comment by Papotito123** [comment]
Hello:
So much thanks.
