### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement msldap>=0.3.20

### ISSUE THREAD

**Issue by freedom-wy** [skelsec/pypykatz#60]
ERROR: Could not find a version that satisfies the requirement msldap>=0.3.20 (from pypykatz) (from versions: 0.0.2, 0.0.3, 0.0.4, 0.1.0, 0.1.1, 0.1.2, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.2.10, 0.2.11, 0.2.12, 0.2.13, 0.2.14, 0.3.0, 0.3.1, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.3.10, 0.3.11, 0.3.12, 0.3.13)
ERROR: No matching distribution found for msldap>=0.3.20 (from pypykatz)

**Comment by RazviAlex** [comment]
I get same issue when install it via pip3. Try clone the repo, Install prerequirements (here you got msladp..) and install it again via python install ` python3 setup.py install`.

**Comment by skelsec** [comment]
This is really strange, the msldap version 0.3.20 was published on the 8th of November onto pip.
I managed to build the entire project using `setup.py install` so at the moment I'm clueless.
Please let me know if you still experience this issue.

**Comment by ukedk** [comment]
pip call with root account told the missing dependency: msldap needs python >= 3.7. I had 3.6 installed (ubuntu 18.04). After setup of python 3.7 pypykatz installed successfully. Hope that helps ;)

**Comment by skelsec** [comment]
Ahh I think I found the issue: msldap package changed the minimum version requirement from 3.6 to 3.7
I believe I should do this to pypykatz as well.

**Comment by skelsec** [comment]
Closing this issue as we've passed multiple version changes since
