### ISSUE TITLE
Signature was not found in module msv1_0.dll

### ISSUE THREAD

**Issue by m7x** [skelsec/pypykatz#61]
Hi there I have this error message when I run:

`pypykatz -vv lsa minidump C:\dump.dmp `

The dump is from a Windows Server 2016 Standard 14393 x64.

pypykatz v0.3.15 was executed on a Windows 10 Enterprise Build 1902.

```
Level 6:pypykatz:[LiveSsp] [decryptor] Failed to find structs! Reason: Signature was not found in module msv1_0.dll Signature: 74258b
Level 6:pypykatz:[Dpapi] [template] Selecting template for list_entry: PKIWI_MASTERKEY_CACHE_ENTRY
Level 6:pypykatz:[Dpapi] [decryptor] Searching for key struct signature
Level 6:pypykatz:[Dpapi] [decryptor] Failed to find structs! Reason: Memory address 0x7ffa7a7b5505 is not in process memory space
```

Any suggestions?

Thanks

**Comment by skelsec** [comment]
It is really hard to tell just from this info. I'll see if I can find the exact same build and test it but it will take some time for sure.

**Comment by skelsec** [comment]
Closing this since I got a thumbs up.
