### ISSUE TITLE
Compilation Instructions

### ISSUE THREAD

**Issue by a7t0fwa7** [skelsec/pypykatz#62]
Hey man, 

I would like to compile my own binary, my question is do you use pyinstaller for this or something else? 

And are there any specific requirements prior to compiling ?

Cheers

**Comment by skelsec** [comment]
Hello,

I use pyinstaller, for the current version there are no specific prerequirements it should work out of the box.

**Comment by Papotito123** [comment]
Hello:
This should be good news.
I tried with the before version,and get compile but doesn't ran.

I'll test later.

Thanks.

**Comment by skelsec** [comment]
Using pyinstaller works, I have my build setup using it.
