### ISSUE TITLE
how to use pypykatz do kerberos::purge

### ISSUE THREAD

**Issue by freedom-wy** [skelsec/pypykatz#63]
how can i use pypykatz do kerberos::purge
when i use mimikatz，i can do kerberos::purge
[https://github.com/skelsec/pypykatz/live_kerberos](url) is 404

**Comment by skelsec** [comment]
Kerberos functionality is currently not available. It will be included in the new version but it is not stable yet.
Expected release date is in a few weeks.

**Comment by freedom-wy** [comment]
Thank you for your reply

**Comment by skelsec** [comment]
The new version now has kerberos purge.
