### ISSUE TITLE
[Feature Request] Parse cleartext RDP credentials from svchost.exe 

### ISSUE THREAD

**Issue by n00py** [skelsec/pypykatz#85]
As documented in this Twitter thread here:

https://twitter.com/jonasLyk/status/1393058962942083076?s=20

**Comment by skelsec** [comment]
I'm still a bit indecisive on whether you'd really want this in Python, but here u go.
https://github.com/skelsec/pypykatz/blob/master/pypykatz/rdp/cmdhelper.py

**Comment by skelsec** [comment]
forgot to close this
